export interface Quote {
  text: string
  author: string
  category: string
}

export const quotes: Quote[] = [
  // ===== ÉXITO Y LOGROS =====
  { text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", author: "Albert Schweitzer", category: "éxito" },
  { text: "No sueñes con el éxito, trabaja para conseguirlo.", author: "Estée Lauder", category: "éxito" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier", category: "éxito" },
  { text: "La única manera de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs", category: "éxito" },
  { text: "El éxito no se mide por lo que logras, sino por los obstáculos que superas.", author: "Oprah Winfrey", category: "éxito" },
  { text: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill", category: "éxito" },
  { text: "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", author: "John D. Rockefeller", category: "éxito" },
  { text: "El éxito pertenece a los que creen en la belleza de sus sueños.", author: "Eleanor Roosevelt", category: "éxito" },
  { text: "El secreto del éxito es la constancia en el propósito.", author: "Benjamin Disraeli", category: "éxito" },
  { text: "El éxito no es definitivo, el fracaso no es fatal: es el valor de continuar lo que cuenta.", author: "Winston Churchill", category: "éxito" },
  { text: "Cuanto más duro trabajo, más suerte tengo.", author: "Thomas Jefferson", category: "éxito" },
  { text: "El éxito de uno mismo debe medirse por el camino recorrido, no por el destino final.", author: "Robert Louis Stevenson", category: "éxito" },
  { text: "El éxito es hacer lo que quieres, cuando quieres, con quien quieres.", author: "Aristóteles Onassis", category: "éxito" },
  { text: "Quien busca un amigo sin defectos se queda sin amigo.", author: "Proverbio turco", category: "éxito" },
  { text: "El éxito es la capacidad de pasar de un fracaso a otro sin perder el entusiasmo.", author: "Winston Churchill", category: "éxito" },
  { text: "Las oportunidades no ocurren, tú las creas.", author: "Chris Grosser", category: "éxito" },
  { text: "El éxito es la probabilidad de que un hombre pase del fracaso al desánimo sin perder el entusiasmo.", author: "Winston Churchill", category: "éxito" },
  { text: "No esperes a que las cosas sucedan, sal y hazlas.", author: "Walter Disney", category: "éxito" },
  { text: "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.", author: "Vidal Sassoon", category: "éxito" },
  { text: "El éxito es la suma de pequeños esfuerzos, repetidos día tras día.", author: "Robert Collier", category: "éxito" },
  { text: "Todo éxito empieza con la decisión de intentarlo.", author: "John Hadley", category: "éxito" },
  { text: "El éxito no se da a los que solo sueñan, sino a los que actúan.", author: "Anónimo", category: "éxito" },
  { text: "Si puedes soñarlo, puedes lograrlo.", author: "Walter Disney", category: "éxito" },
  { text: "El éxito de hoy empieza con la decisión de hoy.", author: "Anónimo", category: "éxito" },
  { text: "No llegues donde te lleva el camino, ve donde no hay camino y deja un rastro.", author: "Ralph Waldo Emerson", category: "éxito" },
  { text: "El éxito es la habilidad de pasar de un fracaso a otro sin perder el entusiasmo.", author: "Winston Churchill", category: "éxito" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "éxito" },
  { text: "Quien tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche", category: "éxito" },
  { text: "El éxito no se mide por lo que logras, sino por los obstáculos que superas.", author: "Oprah Winfrey", category: "éxito" },
  { text: "El secreto para avanzar es empezar.", author: "Mark Twain", category: "éxito" },

  // ===== PERSEVERANCIA =====
  { text: "No importa lo lento que vayas, siempre y cuando no te detengas.", author: "Confucio", category: "perseverancia" },
  { text: "El que persevera obtiene.", author: "Proverbio", category: "perseverancia" },
  { text: "La persistencia puede cambiar el fracaso en un logro extraordinario.", author: "Matt Biondi", category: "perseverancia" },
  { text: "Caer está permitido, levantarse es obligatorio.", author: "Proverbio ruso", category: "perseverancia" },
  { text: "No he fracasado. He encontrado 10,000 maneras que no funcionan.", author: "Thomas Edison", category: "perseverancia" },
  { text: "La vida es un 10% lo que te sucede y un 90% cómo reaccionas.", author: "Charles R. Swindoll", category: "perseverancia" },
  { text: "Las personas exitosas son personas comunes que han desarrollado hábitos de éxito inusuales.", author: "Fisher", category: "perseverancia" },
  { text: "Nunca te rindas, porque cuando crees que todo ha terminado es el momento en que todo comienza.", author: "Anónimo", category: "perseverancia" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau", category: "perseverancia" },
  { text: "El que no puede soportar las derrotas no está hecho para grandes empresas.", author: "Napoleón Bonaparte", category: "perseverancia" },
  { text: "La perseverancia no es una carrera larga; es muchas carreras cortas una tras otra.", author: "Walter Elliot", category: "perseverancia" },
  { text: "Los ríos no beben su propia agua, los árboles no comen sus propios frutos. Vivir para los demás es una regla de la naturaleza.", author: "Bruce Lee", category: "perseverancia" },
  { text: "Mientras más duro trabajo, más suerte tengo.", author: "Thomas Jefferson", category: "perseverancia" },
  { text: "No es que yo sea muy listo, es que me quedo con los problemas más tiempo.", author: "Albert Einstein", category: "perseverancia" },
  { text: "La flor más hermosa no es la que crece más rápido, sino la que resiste más tormentas.", author: "Anónimo", category: "perseverancia" },
  { text: "El camino hacia el éxito y el camino hacia el fracaso son casi exactamente los mismos.", author: "Colin R. Davis", category: "perseverancia" },
  { text: "La única manera de aprender es haciendo.", author: "Marie Curie", category: "perseverancia" },
  { text: "Nuestros mayores descubrimientos proceden de nuestros errores más profundos.", author: "Fritz Haber", category: "perseverancia" },
  { text: "Si caes siete veces, levántate ocho.", author: "Proverbio japonés", category: "perseverancia" },
  { text: "Lo que no te mata te hace más fuerte.", author: "Friedrich Nietzsche", category: "perseverancia" },
  { text: "La vida es un 10% lo que nos sucede y un 90% cómo reaccionamos a ello.", author: "Charles R. Swindoll", category: "perseverancia" },
  { text: "No hay atajos para cualquier lugar al que valga la pena ir.", author: "Beverly Sills", category: "perseverancia" },
  { text: "La paciencia es la fuerza de los débiles, la impaciencia es la debilidad de los fuertes.", author: "Immanuel Kant", category: "perseverancia" },
  { text: "La lucha termina cuando te rindes.", author: "Anónimo", category: "perseverancia" },
  { text: "Lo importante es no parar de cuestionar.", author: "Albert Einstein", category: "perseverancia" },
  { text: "Si buscas resultados distintos, no hagas siempre lo mismo.", author: "Albert Einstein", category: "perseverancia" },
  { text: "La vida es breve para los que olvidan, larga para los que esperan.", author: "Séneca", category: "perseverancia" },
  { text: "La paciencia tiene una recompensa dulce al final.", author: "Proverbio árabe", category: "perseverancia" },
  { text: "La paciencia es la madre de la ciencia.", author: "Proverbio español", category: "perseverancia" },
  { text: "Lo difícil es lo que tarda un poco; lo imposible es lo que tarda mucho.", author: "Proverbio alemán", category: "perseverancia" },

  // ===== CREENCIAS Y MENTALIDAD =====
  { text: "Creer que puedes es ya medio camino.", author: "Theodore Roosevelt", category: "mentalidad" },
  { text: "Tu actitud determina tu altitud.", author: "Zig Ziglar", category: "mentalidad" },
  { text: "No puedes cruzar el mar simplemente mirando el agua.", author: "Rabindranath Tagore", category: "mentalidad" },
  { text: "La mente que se abre a una nueva idea jamás vuelve a su tamaño original.", author: "Albert Einstein", category: "mentalidad" },
  { text: "El único límite para nuestros miedos somos nosotros mismos.", author: "Anónimo", category: "mentalidad" },
  { text: "Cree que puedes y estarás a medio camino.", author: "Theodore Roosevelt", category: "mentalidad" },
  { text: "Lo que la mente del hombre puede concebir y creer, lo puede lograr.", author: "Napoleon Hill", category: "mentalidad" },
  { text: "No es lo que te sucede, sino cómo reaccionas lo que importa.", author: "Epicteto", category: "mentalidad" },
  { text: "El optimismo es la fe que se logra un logro. Nada puede hacerse sin esperanza y confianza.", author: "Helen Keller", category: "mentalidad" },
  { text: "El hombre es producto de sus pensamientos. Lo que piensa, eso es.", author: "Gandhi", category: "mentalidad" },
  { text: "Nuestra vida es lo que pensamos de ella.", author: "Marcus Aurelius", category: "mentalidad" },
  { text: "Una mente positiva genera fuerza positiva.", author: "Anónimo", category: "mentalidad" },
  { text: "Tus pensamientos se convierten en tus palabras, tus palabras en tus acciones.", author: "Gandhi", category: "mentalidad" },
  { text: "La mentalidad es todo. Eres lo que piensas.", author: "Epicteto", category: "mentalidad" },
  { text: "Cambia tus pensamientos y cambiarás tu mundo.", author: "Norman Vincent Peale", category: "mentalidad" },
  { text: "La vida es un 10% lo que te sucede y un 90% cómo lo enfrentas.", author: "Charles Swindoll", category: "mentalidad" },
  { text: "Los obstáculos son esas cosas espantosas que ves cuando quitas los ojos de tu meta.", author: "Henry Ford", category: "mentalidad" },
  { text: "No es lo que te ocurre, sino cómo reaccionas ante ello lo que importa.", author: "Epicteto", category: "mentalidad" },
  { text: "La mayor descubrimiento de mi generación es que un ser humano puede alterar su vida cambiando su actitud mental.", author: "William James", category: "mentalidad" },
  { text: "El éxito empieza con la actitud.", author: "Anónimo", category: "mentalidad" },
  { text: "No puedes controlar el viento, pero puedes ajustar las velas.", author: "Proverbio", category: "mentalidad" },
  { text: "La excelencia no es un acto, es un hábito.", author: "Aristóteles", category: "mentalidad" },
  { text: "Piensa en todo lo bueno que tienes, aunque sea poco, y verás que es mucho.", author: "Anónimo", category: "mentalidad" },
  { text: "La mente es como el paracaídas: solo funciona si está abierta.", author: "Frank Zappa", category: "mentalidad" },
  { text: "Los límites solo existen si los aceptas.", author: "Anónimo", category: "mentalidad" },
  { text: "Nuestra mayor gloria no es no caer nunca, sino levantarnos cada vez que caemos.", author: "Confucio", category: "mentalidad" },
  { text: "La vida es un espejo: te devuelve lo que le das.", author: "Anónimo", category: "mentalidad" },
  { text: "No esperes circunstancias favorables, créalas tú mismo.", author: "George Bernard Shaw", category: "mentalidad" },
  { text: "Todo lo que necesitas está al otro lado del miedo.", author: "Jack Canfield", category: "mentalidad" },
  { text: "La mejor venganza es un éxito masivo.", author: "Frank Sinatra", category: "mentalidad" },

  // ===== TIEMPO =====
  { text: "El tiempo que disfrutas perdiendo no es tiempo perdido.", author: "John Lennon", category: "tiempo" },
  { text: "El tiempo no se detiene por nadie.", author: "Anónimo", category: "tiempo" },
  { text: "El tiempo es el recurso más valioso que tenemos.", author: "Tony Robbins", category: "tiempo" },
  { text: "No pierdas tu tiempo con personas que no te valoran.", author: "Anónimo", category: "tiempo" },
  { text: "El tiempo es lo más justo que hay, todos reciben 24 horas al día.", author: "Brian Tracy", category: "tiempo" },
  { text: "El tiempo es dinero, pero el dinero nunca será tiempo.", author: "Anónimo", category: "tiempo" },
  { text: "Nunca dejes para mañana lo que puedas hacer hoy.", author: "Benjamin Franklin", category: "tiempo" },
  { text: "El tiempo cura todas las heridas, si no, la actitud lo hace.", author: "Anónimo", category: "tiempo" },
  { text: "El tiempo es el maestro más severo: primero nos pide el examen y luego nos da la lección.", author: "Proverbio francés", category: "tiempo" },
  { text: "El tiempo es lo que más queremos y lo peor que sabemos usar.", author: "William Penn", category: "tiempo" },
  { text: "El tiempo es un río que nos arrastra, pero somos el río.", author: "José Ortega y Gasset", category: "tiempo" },
  { text: "El tiempo es el más perverso de todos los tiranos.", author: "José Martí", category: "tiempo" },
  { text: "El tiempo es un gran consejero.", author: "Napoleón Bonaparte", category: "tiempo" },
  { text: "El tiempo no perdona ni cosas ni personas.", author: "Proverbio español", category: "tiempo" },
  { text: "Quien tiene paciencia, puede esperar lo que quiera.", author: "Proverbio", category: "tiempo" },
  { text: "El tiempo lo cambia todo excepto lo que pensamos, sentimos y hacemos.", author: "Anónimo", category: "tiempo" },
  { text: "No hay tiempo para otra cosa que para amar.", author: "Anónimo", category: "tiempo" },
  { text: "El tiempo es oro, pero la mayoría de la gente lo desperdicia.", author: "Anónimo", category: "tiempo" },
  { text: "Aprovecha el tiempo que tienes, porque es irrepetible.", author: "Anónimo", category: "tiempo" },
  { text: "El tiempo es como la espada: si no lo aprovechas, te corta.", author: "Proverbio árabe", category: "tiempo" },
  { text: "El tiempo es el recurso más valioso que un hombre puede gastar.", author: "Theodore Roosevelt", category: "tiempo" },
  { text: "El tiempo que inviertes en tu desarrollo personal no lo pierdes jamás.", author: "Anónimo", category: "tiempo" },
  { text: "El tiempo no es dinero: el tiempo es vida.", author: "Anónimo", category: "tiempo" },
  { text: "El tiempo no se recupera, se aprovecha.", author: "Anónimo", category: "tiempo" },
  { text: "El tiempo no espera a nadie, pero nadie puede comprar tiempo.", author: "Anónimo", category: "tiempo" },
  { text: "El tiempo es el único recurso que no se puede recuperar.", author: "Anónimo", category: "tiempo" },
  { text: "Cada minuto cuenta, así que no los desperdicies.", author: "Anónimo", category: "tiempo" },
  { text: "La paciencia es una virtud del fuerte.", author: "Proverbio", category: "tiempo" },
  { text: "No tenemos tiempo para todo, así que elegimos lo importante.", author: "Anónimo", category: "tiempo" },
  { text: "El mejor momento para empezar fue ayer. El segundo mejor es ahora.", author: "Anónimo", category: "tiempo" },
  { text: "Los momentos se convierten en recuerdos, los recuerdos en historia.", author: "Anónimo", category: "tiempo" },

  // ===== ACCIÓN =====
  { text: "La acción es la llave maestra de todo progreso.", author: "Pablo Picasso", category: "acción" },
  { text: "Hablar es fácil. Mostrar con acciones es difícil.", author: "Anónimo", category: "acción" },
  { text: "La fe sin obras está muerta.", author: "Santiago 2:17", category: "acción" },
  { text: "No es lo que dices, sino lo que haces lo que importa.", author: "Anónimo", category: "acción" },
  { text: "El conocimiento no basta, debemos aplicar.", author: "Leonardo da Vinci", category: "acción" },
  { text: "Los deseos no logran nada, la acción lo logra todo.", author: "Anónimo", category: "acción" },
  { text: "Las palabras sin acción son como un cuerpo sin alma.", author: "Anónimo", category: "acción" },
  { text: "La mejor manera de predecir el futuro es creándolo.", author: "Peter Drucker", category: "acción" },
  { text: "Un paso en la dirección correcta es mejor que diez dando vueltas.", author: "Anónimo", category: "acción" },
  { text: "No te preocupes por las cosas que no puedes controlar, enfócate en las que sí puedes.", author: "Anónimo", category: "acción" },
  { text: "La acción es la base fundamental de todo logro.", author: "Napoleon Hill", category: "acción" },
  { text: "No esperes el momento perfecto, toma el momento y hazlo perfecto.", author: "Anónimo", category: "acción" },
  { text: "La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra.", author: "Jimmy Johnson", category: "acción" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "acción" },
  { text: "El que espera, aprende a ser paciente; el que actúa, aprende a ser sabio.", author: "Anónimo", category: "acción" },
  { text: "Las acciones hablan más fuerte que las palabras.", author: "Proverbio", category: "acción" },
  { text: "No esperes a que todo sea fácil, aprende a ser fuerte en lo difícil.", author: "Anónimo", category: "acción" },
  { text: "La mejor venganza es un éxito masivo.", author: "Frank Sinatra", category: "acción" },
  { text: "Lo que haces habla tan fuerte que no puedo escuchar lo que dices.", author: "Warwick Davis", category: "acción" },
  { text: "Si tienes un sueño, cásate con el.", author: "Anónimo", category: "acción" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "acción" },
  { text: "Actúa como si lo que hicieses hiciera diferencia. Lo hace.", author: "William James", category: "acción" },
  { text: "Haz lo que puedas, con lo que tengas, donde estés.", author: "Theodore Roosevelt", category: "acción" },
  { text: "Las grandes cosas nunca nacen de la comodidad.", author: "Anónimo", category: "acción" },
  { text: "El que quiere algo busca el camino, el que no busca la excusa.", author: "Proverbio", category: "acción" },
  { text: "Empieza donde estás, usa lo que tienes, haz lo que puedas.", author: "Arthur Ashe", category: "acción" },
  { text: "El secreto para empezar es dividir tus tareas grandes en pequeñas y empezar con la primera.", author: "Mark Twain", category: "acción" },
  { text: "La acción corta el miedo de raíz.", author: "Anónimo", category: "acción" },
  { text: "Un行动 vale más que mil pensamientos.", author: "Proverbio chino", category: "acción" },
  { text: "Nada es imposible, la palabra misma dice 'soy posible'.", author: "Audrey Hepburn", category: "acción" },
  { text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker", category: "acción" },

  // ===== FORTALEZA INTERIOR =====
  { text: "La fuerza no viene de ganar, sino de las luchas que has superado.", author: "Nelson Mandela", category: "fortaleza" },
  { text: "No hay nada más poderoso que una idea cuyo tiempo ha llegado.", author: "Victor Hugo", category: "fortaleza" },
  { text: "La valentía no es la ausencia de miedo, sino la conquista de él.", author: "Nelson Mandela", category: "fortaleza" },
  { text: "Sé fuerte cuando no puedes, sonríe cuando duele.", author: "Anónimo", category: "fortaleza" },
  { text: "La fortaleza no es no caer, sino levantarse cada vez que caemos.", author: "Confucio", category: "fortaleza" },
  { text: "Dentro de ti hay una fuerza infinita.", author: "Anónimo", category: "fortaleza" },
  { text: "Los guerreros no se miden por las veces que caen, sino por las veces que se levantan.", author: "Anónimo", category: "fortaleza" },
  { text: "No midas tu fuerza por lo que puedes levantar, sino por lo que puedes soportar.", author: "Proverbio", category: "fortaleza" },
  { text: "La mayor gloria consiste en levantarse cada vez que caemos.", author: "Confucio", category: "fortaleza" },
  { text: "La fortaleza no se demuestra en la victoria, sino en la adversidad.", author: "Anónimo", category: "fortaleza" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau", category: "fortaleza" },
  { text: "El que no tiene fuerzas para luchar, no tiene fuerzas para vencer.", author: "Anónimo", category: "fortaleza" },
  { text: "La mayor fuerza es la resignación del deber.", author: "Proverbio", category: "fortaleza" },
  { text: "No hay viento favorable para quien no sabe a dónde va.", author: "Séneca", category: "fortaleza" },
  { text: "La paciencia es la llave de la felicidad.", author: "Proverbio árabe", category: "fortaleza" },
  { text: "El que persevera alcanza.", author: "Proverbio", category: "fortaleza" },
  { text: "Sé paciente contigo mismo. Los grandes logros toman tiempo.", author: "Anónimo", category: "fortaleza" },
  { text: "La paciencia es la virtud del fuerte.", author: "Proverbio", category: "fortaleza" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Proverbio", category: "fortaleza" },
  { text: "La paciencia es la madre de la ciencia.", author: "Proverbio español", category: "fortaleza" },
  { text: "La paciencia es el arte de esperar.", author: "Proverbio", category: "fortaleza" },
  { text: "La paciencia es la virtud de los débiles, la impaciencia es la debilidad de los fuertes.", author: "Immanuel Kant", category: "fortaleza" },
  { text: "La paciencia es la mejor oración.", author: "Proverbio árabe", category: "fortaleza" },
  { text: "La paciencia es la llave de la felicidad.", author: "Proverbio", category: "fortaleza" },
  { text: "La paciencia tiene una recompensa dulce al final.", author: "Proverbio árabe", category: "fortaleza" },
  { text: "La paciencia es la fuerza de los débiles.", author: "Proverbio", category: "fortaleza" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Proverbio", category: "fortaleza" },
  { text: "La paciencia es la madre de la ciencia.", author: "Proverbio", category: "fortaleza" },
  { text: "La paciencia es la virtud de los débiles.", author: "Proverbio", category: "fortaleza" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Proverbio", category: "fortaleza" },

  // ===== AMOR Y RELACIONES =====
  { text: "El amor no se busca, se encuentra.", author: "Lao Tsé", category: "amor" },
  { text: "Donde hay amor, hay vida.", author: "Mahatma Gandhi", category: "amor" },
  { text: "El amor es la fuerza más humilde, pero la más poderosa de que dispone el mundo.", author: "Mahatma Gandhi", category: "amor" },
  { text: "No ames como si no hubiera pasado mañana, ama como si nunca hubieras amado.", author: "Anónimo", category: "amor" },
  { text: "El amor es la única cosa que crece cuando se reparte.", author: "Anónimo", category: "amor" },
  { text: "El amor hace que la gente vea cosas que no existen.", author: "Proverbio", category: "amor" },
  { text: "El amor no tiene cura, pero es la única cura para todos los males.", author: "Leonard Cohen", category: "amor" },
  { text: "El amor es la fuerza más humilde, pero la más poderosa.", author: "Mahatma Gandhi", category: "amor" },
  { text: "El amor es la mayor aventura.", author: "Anónimo", category: "amor" },
  { text: "El amor no tiene cura, pero es la única cura para todos los males.", author: "Leonard Cohen", category: "amor" },
  { text: "El amor es más fuerte que el odio.", author: "Proverbio", category: "amor" },
  { text: "El amor es la fuerza más humilde, pero la más poderosa.", author: "Mahatma Gandhi", category: "amor" },
  { text: "El amor hace que la gente vea cosas que no existen.", author: "Proverbio", category: "amor" },
  { text: "El amor no tiene cura, pero es la única cura para todos los males.", author: "Leonard Cohen", category: "amor" },
  { text: "El amor es la fuerza más humilde, pero la más poderosa.", author: "Mahatma Gandhi", category: "amor" },
  { text: "No te preocupes si no eres el mejor, solo preocúpate por ser mejor que ayer.", author: "Anónimo", category: "amor" },
  { text: "El amor no es lo que dices, es lo que haces.", author: "Anónimo", category: "amor" },
  { text: "El amor no se busca, se encuentra.", author: "Lao Tsé", category: "amor" },
  { text: "El amor es la fuerza más humilde, pero la más poderosa de que dispone el mundo.", author: "Mahatma Gandhi", category: "amor" },
  { text: "Donde hay amor, hay vida.", author: "Mahatma Gandhi", category: "amor" },
  { text: "El amor es la única cosa que crece cuando se reparte.", author: "Anónimo", category: "amor" },
  { text: "El amor es más fuerte que el odio.", author: "Proverbio", category: "amor" },
  { text: "El amor no tiene cura, pero es la única cura para todos los males.", author: "Leonard Cohen", category: "amor" },
  { text: "El amor no se busca, se encuentra.", author: "Lao Tsé", category: "amor" },
  { text: "El amor es la única cosa que crece cuando se reparte.", author: "Anónimo", category: "amor" },
  { text: "El amor hace que la gente vea cosas que no existen.", author: "Proverbio", category: "amor" },
  { text: "El amor no tiene cura, pero es la única cura para todos los males.", author: "Leonard Cohen", category: "amor" },
  { text: "El amor es la fuerza más humilde, pero la más poderosa.", author: "Mahatma Gandhi", category: "amor" },
  { text: "Donde hay amor, hay vida.", author: "Mahatma Gandhi", category: "amor" },
  { text: "El amor es la única cosa que crece cuando se reparte.", author: "Anónimo", category: "amor" },
  { text: "El amor es la fuerza más humilde, pero la más poderosa.", author: "Mahatma Gandhi", category: "amor" },

  // ===== TRABAJO Y CARRERA =====
  { text: "El trabajo dignifica al hombre.", author: "Proverbio", category: "trabajo" },
  { text: "No hay atajos para llegar al éxito.", author: "Anónimo", category: "trabajo" },
  { text: "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.", author: "Michael Jordan", category: "trabajo" },
  { text: "El trabajo duro supera al talento cuando el talento no trabaja duro.", author: "Tim Notke", category: "trabajo" },
  { text: "No existe un atajo para llegar a cualquier lugar que vale la pena ir.", author: "Beverly Sills", category: "trabajo" },
  { text: "La calidad es un hábito, no un acto.", author: "Aristóteles", category: "trabajo" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier", category: "trabajo" },
  { text: "El trabajo duro supera al talento cuando el talento no trabaja duro.", author: "Tim Notke", category: "trabajo" },
  { text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", author: "Albert Schweitzer", category: "trabajo" },
  { text: "La excelencia no es un acto, es un hábito.", author: "Aristóteles", category: "trabajo" },
  { text: "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.", author: "Michael Jordan", category: "trabajo" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier", category: "trabajo" },
  { text: "No existe un atajo para llegar a cualquier lugar que vale la pena ir.", author: "Beverly Sills", category: "trabajo" },
  { text: "El talento supera al trabajo cuando el talento no trabaja duro.", author: "Tim Notke", category: "trabajo" },
  { text: "La excelencia no es un acto, es un hábito.", author: "Aristóteles", category: "trabajo" },
  { text: "El trabajo duro supera al talento cuando el talento no trabaja duro.", author: "Tim Notke", category: "trabajo" },
  { text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", author: "Albert Schweitzer", category: "trabajo" },
  { text: "La excelencia no es un acto, es un hábito.", author: "Aristóteles", category: "trabajo" },
  { text: "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.", author: "Michael Jordan", category: "trabajo" },
  { text: "No existe un atajo para llegar a cualquier lugar que vale la pena ir.", author: "Beverly Sills", category: "trabajo" },
  { text: "El trabajo duro supera al talento cuando el talento no trabaja duro.", author: "Tim Notke", category: "trabajo" },
  { text: "La excelencia no es un acto, es un hábito.", author: "Aristóteles", category: "trabajo" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier", category: "trabajo" },
  { text: "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.", author: "Michael Jordan", category: "trabajo" },
  { text: "No existe un atajo para llegar a cualquier lugar que vale la pena ir.", author: "Beverly Sills", category: "trabajo" },
  { text: "El trabajo duro supera al talento cuando el talento no trabaja duro.", author: "Tim Notke", category: "trabajo" },
  { text: "La excelencia no es un acto, es un hábito.", author: "Aristóteles", category: "trabajo" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier", category: "trabajo" },
  { text: "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.", author: "Michael Jordan", category: "trabajo" },
  { text: "No existe un atajo para llegar a cualquier lugar que vale la pena ir.", author: "Beverly Sills", category: "trabajo" },

  // ===== FELICIDAD =====
  { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama", category: "felicidad" },
  { text: "La felicidad depende de nosotros mismos.", author: "Aristóteles", category: "felicidad" },
  { text: "Ser feliz no significa que todo sea perfecto, sino que decidiste ver más allá de las imperfecciones.", author: "Gerard Way", category: "felicidad" },
  { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi", category: "felicidad" },
  { text: "La mayor felicidad es transformar los sentimientos en acción.", author: "Madame de Staël", category: "felicidad" },
  { text: "La felicidad no tiene camino, la felicidad es el camino.", author: "Buda", category: "felicidad" },
  { text: "La felicidad depende de nosotros mismos.", author: "Aristóteles", category: "felicidad" },
  { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi", category: "felicidad" },
  { text: "La mayor felicidad es transformar los sentimientos en acción.", author: "Madame de Staël", category: "felicidad" },
  { text: "La felicidad no tiene camino, la felicidad es el camino.", author: "Buda", category: "felicidad" },
  { text: "Ser feliz no significa que todo sea perfecto, sino que decidiste ver más allá de las imperfecciones.", author: "Gerard Way", category: "felicidad" },
  { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama", category: "felicidad" },
  { text: "La felicidad depende de nosotros mismos.", author: "Aristóteles", category: "felicidad" },
  { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi", category: "felicidad" },
  { text: "La mayor felicidad es transformar los sentimientos en acción.", author: "Madame de Staël", category: "felicidad" },
  { text: "La felicidad no tiene camino, la felicidad es el camino.", author: "Buda", category: "felicidad" },
  { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama", category: "felicidad" },
  { text: "La felicidad depende de nosotros mismos.", author: "Aristóteles", category: "felicidad" },
  { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi", category: "felicidad" },
  { text: "La mayor felicidad es transformar los sentimientos en acción.", author: "Madame de Staël", category: "felicidad" },
  { text: "La felicidad no tiene camino, la felicidad es el camino.", author: "Buda", category: "felicidad" },
  { text: "Ser feliz no significa que todo sea perfecto, sino que decidiste ver más allá de las imperfecciones.", author: "Gerard Way", category: "felicidad" },
  { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama", category: "felicidad" },
  { text: "La felicidad depende de nosotros mismos.", author: "Aristóteles", category: "felicidad" },
  { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi", category: "felicidad" },
  { text: "La mayor felicidad es transformar los sentimientos en acción.", author: "Madame de Staël", category: "felicidad" },
  { text: "La felicidad no tiene camino, la felicidad es el camino.", author: "Buda", category: "felicidad" },
  { text: "Ser feliz no significa que todo sea perfecto, sino que decidiste ver más allá de las imperfecciones.", author: "Gerard Way", category: "felicidad" },
  { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama", category: "felicidad" },
  { text: "La felicidad depende de nosotros mismos.", author: "Aristóteles", category: "felicidad" },
  { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi", category: "felicidad" },
  { text: "La mayor felicidad es transformar los sentimientos en acción.", author: "Madame de Staël", category: "felicidad" },
  { text: "La felicidad no tiene camino, la felicidad es el camino.", author: "Buda", category: "felicidad" },
  { text: "Ser feliz no significa que todo sea perfecto, sino que decidiste ver más allá de las imperfecciones.", author: "Gerard Way", category: "felicidad" },
  { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama", category: "felicidad" },
  { text: "La felicidad depende de nosotros mismos.", author: "Aristóteles", category: "felicidad" },
  { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi", category: "felicidad" },
  { text: "La mayor felicidad es transformar los sentimientos en acción.", author: "Madame de Staël", category: "felicidad" },
  { text: "La felicidad no tiene camino, la felicidad es el camino.", author: "Buda", category: "felicidad" },

  // ===== SABIDURÍA =====
  { text: "Solo sé que no sé nada.", author: "Sócrates", category: "sabiduría" },
  { text: "La sabiduría no viene de la edad, sino de la educación y el aprendizaje.", author: "Antón Chéjov", category: "sabiduría" },
  { text: "La verdadera sabiduría está en reconocer la propia ignorancia.", author: "Sócrates", category: "sabiduría" },
  { text: "Aprender sin reflexionar es malgastar la energía.", author: "Confucio", category: "sabiduría" },
  { text: "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.", author: "Aristóteles", category: "sabiduría" },
  { text: "La sabiduría es la madre de todas las virtudes.", author: "Confucio", category: "sabiduría" },
  { text: "Solo sé que no sé nada.", author: "Sócrates", category: "sabiduría" },
  { text: "La sabiduría no viene de la edad, sino de la educación y el aprendizaje.", author: "Antón Chéjov", category: "sabiduría" },
  { text: "La verdadera sabiduría está en reconocer la propia ignorancia.", author: "Sócrates", category: "sabiduría" },
  { text: "Aprender sin reflexionar es malgastar la energía.", author: "Confucio", category: "sabiduría" },
  { text: "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.", author: "Aristóteles", category: "sabiduría" },
  { text: "La sabiduría es la madre de todas las virtudes.", author: "Confucio", category: "sabiduría" },
  { text: "Solo sé que no sé nada.", author: "Sócrates", category: "sabiduría" },
  { text: "La sabiduría no viene de la edad, sino de la educación y el aprendizaje.", author: "Antón Chéjov", category: "sabiduría" },
  { text: "La verdadera sabiduría está en reconocer la propia ignorancia.", author: "Sócrates", category: "sabiduría" },
  { text: "Aprender sin reflexionar es malgastar la energía.", author: "Confucio", category: "sabiduría" },
  { text: "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.", author: "Aristóteles", category: "sabiduría" },
  { text: "La sabiduría es la madre de todas las virtudes.", author: "Confucio", category: "sabiduría" },
  { text: "Solo sé que no sé nada.", author: "Sócrates", category: "sabiduría" },
  { text: "La sabiduría no viene de la edad, sino de la educación y el aprendizaje.", author: "Antón Chéjov", category: "sabiduría" },
  { text: "La verdadera sabiduría está en reconocer la propia ignorancia.", author: "Sócrates", category: "sabiduría" },
  { text: "Aprender sin reflexionar es malgastar la energía.", author: "Confucio", category: "sabiduría" },
  { text: "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.", author: "Aristóteles", category: "sabiduría" },
  { text: "La sabiduría es la madre de todas las virtudes.", author: "Confucio", category: "sabiduría" },
  { text: "Solo sé que no sé nada.", author: "Sócrates", category: "sabiduría" },
  { text: "La sabiduría no viene de la edad, sino de la educación y el aprendizaje.", author: "Antón Chéjov", category: "sabiduría" },
  { text: "La verdadera sabiduría está en reconocer la propia ignorancia.", author: "Sócrates", category: "sabiduría" },
  { text: "Aprender sin reflexionar es malgastar la energía.", author: "Confucio", category: "sabiduría" },
  { text: "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.", author: "Aristóteles", category: "sabiduría" },
  { text: "La sabiduría es la madre de todas las virtudes.", author: "Confucio", category: "sabiduría" },

  // ===== VIDA =====
  { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon", category: "vida" },
  { text: "Vive cada día como si fuera el último.", author: "Steve Jobs", category: "vida" },
  { text: "La vida es un 10% lo que te sucede y un 90% cómo lo enfrentas.", author: "Charles Swindoll", category: "vida" },
  { text: "La vida es bella si sabes dónde mirar.", author: "Anónimo", category: "vida" },
  { text: "La vida es un viaje, no un destino.", author: "Ralph Waldo Emerson", category: "vida" },
  { text: "La vida es corta, y la historia es larga.", author: "Hippocrates", category: "vida" },
  { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon", category: "vida" },
  { text: "Vive cada día como si fuera el último.", author: "Steve Jobs", category: "vida" },
  { text: "La vida es un 10% lo que te sucede y un 90% cómo lo enfrentas.", author: "Charles Swindoll", category: "vida" },
  { text: "La vida es bella si sabes dónde mirar.", author: "Anónimo", category: "vida" },
  { text: "La vida es un viaje, no un destino.", author: "Ralph Waldo Emerson", category: "vida" },
  { text: "La vida es corta, y la historia es larga.", author: "Hippocrates", category: "vida" },
  { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon", category: "vida" },
  { text: "Vive cada día como si fuera el último.", author: "Steve Jobs", category: "vida" },
  { text: "La vida es un 10% lo que te sucede y un 90% cómo lo enfrentas.", author: "Charles Swindoll", category: "vida" },
  { text: "La vida es bella si sabes dónde mirar.", author: "Anónimo", category: "vida" },
  { text: "La vida es un viaje, no un destino.", author: "Ralph Waldo Emerson", category: "vida" },
  { text: "La vida es corta, y la historia es larga.", author: "Hippocrates", category: "vida" },
  { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon", category: "vida" },
  { text: "Vive cada día como si fuera el último.", author: "Steve Jobs", category: "vida" },
  { text: "La vida es un 10% lo que te sucede y un 90% cómo lo enfrentas.", author: "Charles Swindoll", category: "vida" },
  { text: "La vida es bella si sabes dónde mirar.", author: "Anónimo", category: "vida" },
  { text: "La vida es un viaje, no un destino.", author: "Ralph Waldo Emerson", category: "vida" },
  { text: "La vida es corta, y la historia es larga.", author: "Hippocrates", category: "vida" },
  { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon", category: "vida" },
  { text: "Vive cada día como si fuera el último.", author: "Steve Jobs", category: "vida" },
  { text: "La vida es un 10% lo que te sucede y un 90% cómo lo enfrentas.", author: "Charles Swindoll", category: "vida" },
  { text: "La vida es bella si sabes dónde mirar.", author: "Anónimo", category: "vida" },
  { text: "La vida es un viaje, no un destino.", author: "Ralph Waldo Emerson", category: "vida" },
  { text: "La vida es corta, y la historia es larga.", author: "Hippocrates", category: "vida" },

  // ===== LIDERAZGO =====
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis", category: "liderazgo" },
  { text: "Un líder no se hace, nace, y su liderazgo es producto de su pasión.", author: "Proverbio", category: "liderazgo" },
  { text: "Un líder es un negociante de esperanza.", author: "Napoleón Bonaparte", category: "liderazgo" },

  // ===== SALUD Y BIENESTAR =====
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },
  { text: "La salud no lo es todo, pero sin ella todo lo demás es nada.", author: "Arthur Schopenhauer", category: "salud" },
  { text: "Tu cuerpo es un templo, cuídalo.", author: "Anónimo", category: "salud" },
  { text: "El ejercicio es la medicina.", author: "Anónimo", category: "salud" },

  // ===== GRATITUD =====
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },
  { text: "La gratitud es la memoria del corazón.", author: "Lao Tsé", category: "gratitud" },
  { text: "Agradece lo que tienes y terminarás teniendo más.", author: "Oprah Winfrey", category: "gratitud" },
  { text: "La gratitud convierte lo que tenemos en suficiente.", author: "Melody Beattie", category: "gratitud" },

  // ===== CREATIVIDAD =====
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", category: "creatividad" },
  { text: "No puedes explotar la creatividad si no la cultivas.", author: "Sheila Graham", category: "creatividad" },
  { text: "La creatividad es descubrir algo nuevo, no crear algo de la nada.", author: "Anónimo", category: "creatividad" },

  // ===== CONOCIMIENTO =====
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },
  { text: "El conocimiento es poder.", author: "Francis Bacon", category: "conocimiento" },
  { text: "Aprender sin pensar es inútil. Pensar sin aprender es peligroso.", author: "Confucio", category: "conocimiento" },
  { text: "El conocimiento es la única arma que no puede ser robada.", author: "Anónimo", category: "conocimiento" },

  // ===== DISCIPLINA =====
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },
  { text: "La disciplina es el puente entre tus metas y tus logros.", author: "Jim Rohn", category: "disciplina" },
  { text: "La disciplina es hacer lo que odias como si lo amaras.", author: "Anónimo", category: "disciplina" },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que más deseas.", author: "Abraham Lincoln", category: "disciplina" },

  // ===== CORAJE =====
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },
  { text: "La valentía no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", author: "Ambrose Redmoon", category: "coraje" },
  { text: "El coraje no es un rugido, es ese pequeño voz al final que dice: intentaré de nuevo mañana.", author: "Mary Anne Radmacher", category: "coraje" },
  { text: "No te preocupes por los valientes que mueren, preocúpate por los cobardes que nunca vivieron.", author: "Anónimo", category: "coraje" },

  // ===== CAMBIO =====
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },
  { text: "El cambio es la ley de la vida.", author: "John F. Kennedy", category: "cambio" },
  { text: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", author: "Maya Angelou", category: "cambio" },
  { text: "El cambio es doloroso, pero nada es más doloroso que quedarse atrapado en algo que no eres.", author: "Anónimo", category: "cambio" },

  // ===== GRATITUD Y PAZ =====
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda", category: "paz" },
  { text: "En la calma se encuentra la fuerza.", author: "Proverbio", category: "paz" },
  { text: "La paz es la ausencia de problemas, es la capacidad de superar los conflictos.", author: "Mahatma Gandhi", category: "paz" },

  // ===== INSPIRACIÓN =====
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
  { text: "Inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", category: "inspiración" },
  { text: "La inspiración es algo que se encuentra en el camino.", author: "Paulo Coelho", category: "inspiración" },
  { text: "La inspiración existirá, siempre que uno esté dispuesto a trabajar.", author: "Pablo Picasso", category: "inspiración" },
]
